In [5]:
import numpy as np

In [6]:
vector_1d = np.arange(1, 11)
print("Вектор з першими 10-ма натуральними числами:\n", vector_1d)

Вектор з першими 10-ма натуральними числами:
 [ 1  2  3  4  5  6  7  8  9 10]


In [7]:
matrix_3x3 = np.zeros((3, 3))
print("\nМатриця 3x3, заповнена нулями:\n", matrix_3x3)


Матриця 3x3, заповнена нулями:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
matrix_5x5 = np.random.randint(1, 11, size=(5, 5))
print("\nМасив 5x5, заповнений випадковими цілими числами від 1 до 10:\n", matrix_5x5)


Масив 5x5, заповнений випадковими цілими числами від 1 до 10:
 [[7 5 1 3 3]
 [2 6 1 8 5]
 [4 9 5 3 8]
 [6 2 1 5 1]
 [8 7 3 9 3]]


In [9]:
matrix_4x4 = np.random.rand(4, 4)
print("\nМасив 4x4, заповнений випадковими дійсними числами від 0 до 1:\n", matrix_4x4)


Масив 4x4, заповнений випадковими дійсними числами від 0 до 1:
 [[0.98011052 0.1315524  0.29586241 0.52272388]
 [0.78860603 0.34085893 0.52558154 0.28908996]
 [0.90873925 0.30934355 0.55920462 0.51200051]
 [0.89311095 0.65344578 0.25408594 0.96291154]]


In [10]:
vector_a = np.random.randint(1, 11, size=5)
vector_b = np.random.randint(1, 11, size=5)
addition = vector_a + vector_b
subtraction = vector_a - vector_b
multiplication = vector_a * vector_b
print("\nВектор A:\n", vector_a)
print("Вектор B:\n", vector_b)
print("Додавання:\n", addition)
print("Віднімання:\n", subtraction)
print("Множення:\n", multiplication)



Вектор A:
 [ 3  8  5 10  4]
Вектор B:
 [3 7 7 7 2]
Додавання:
 [ 6 15 12 17  6]
Віднімання:
 [ 0  1 -2  3  2]
Множення:
 [ 9 56 35 70  8]


In [11]:
vector_c = np.random.random(7)
vector_d = np.random.random(7)
dot_product = np.dot(vector_c, vector_d)
print("\nВектор C:\n", vector_c)
print("Вектор D:\n", vector_d)
print("Скалярний добуток:\n", dot_product)


Вектор C:
 [0.71540173 0.16633607 0.16713278 0.67463303 0.1033195  0.75293192
 0.89072864]
Вектор D:
 [0.90268414 0.20419299 0.7824276  0.00437767 0.83054695 0.35831095
 0.66884177]
Скалярний добуток:
 1.7648210591081481


In [13]:
matrix_1 = np.random.randint(1, 11, size=(2, 2))
matrix_2 = np.random.randint(1, 11, size=(2, 3))
matrix_product = np.dot(matrix_1, matrix_2)
print("\nМатриця 1:\n", matrix_1)
print("Матриця 2:\n", matrix_2)
print("Добуток матриць 1 та 2:\n", matrix_product)


Матриця 1:
 [[10  9]
 [ 8  3]]
Матриця 2:
 [[6 5 7]
 [2 6 8]]
Добуток матриць 1 та 2:
 [[ 78 104 142]
 [ 54  58  80]]


In [14]:
matrix_a = np.random.randint(1, 11, size=(3, 3))
inverse_matrix_a = np.linalg.inv(matrix_a)
print("\nМатриця A:\n", matrix_a)
print("Обернена матриця A:\n", inverse_matrix_a)


Матриця A:
 [[ 9  6 10]
 [10  5 10]
 [ 1  9  4]]
Обернена матриця A:
 [[-1.75   1.65   0.25 ]
 [-0.75   0.65   0.25 ]
 [ 2.125 -1.875 -0.375]]


In [15]:
matrix_a = np.random.rand(4, 4)
transposed_matrix_a = np.transpose(matrix_a)
print("\nМатриця A:\n", matrix_a)
print("Транспонована матриця A:\n", transposed_matrix_a)


Матриця A:
 [[0.98291695 0.70317152 0.80094582 0.35916449]
 [0.22667572 0.20101228 0.51886808 0.75842835]
 [0.60917067 0.25116937 0.291104   0.57401423]
 [0.14936429 0.39853904 0.6042798  0.17103793]]
Транспонована матриця A:
 [[0.98291695 0.22667572 0.60917067 0.14936429]
 [0.70317152 0.20101228 0.25116937 0.39853904]
 [0.80094582 0.51886808 0.291104   0.6042798 ]
 [0.35916449 0.75842835 0.57401423 0.17103793]]


In [16]:
matrix_i = np.random.randint(1, 11, size=(3, 4))
vector_e = np.random.randint(1, 11, size=4)
matrix_vector_product = np.dot(matrix_i, vector_e)
print("\nМатриця I:\n", matrix_i)
print("Вектор E:\n", vector_e)
print("Добуток матриці I та вектора E:\n", matrix_vector_product)


Матриця I:
 [[ 1  9  7  8]
 [ 6 10  3  2]
 [ 7  5 10 10]]
Вектор E:
 [ 5  5  8 10]
Добуток матриці I та вектора E:
 [186 124 240]


In [17]:
matrix_j = np.random.rand(2, 3)
vector_f = np.random.rand(3)
matrix_vector_product_j = np.dot(matrix_j, vector_f)
print("\nМатриця J:\n", matrix_j)
print("Вектор F:\n", vector_f)
print("Добуток матриці J та вектора F:\n", matrix_vector_product_j)


Матриця J:
 [[0.16165409 0.73665124 0.85397242]
 [0.80716995 0.33233723 0.77007614]]
Вектор F:
 [0.81899636 0.91441944 0.02536759]
Добуток матриці J та вектора F:
 [0.82766555 0.98449984]


In [18]:
matrix_k = np.random.randint(1, 11, size=(2, 2))
matrix_l = np.random.randint(1, 11, size=(2, 2))
elementwise_multiplication = matrix_k * matrix_l
print("\nМатриця K:\n", matrix_k)
print("Матриця L:\n", matrix_l)
print("Поелементне множення матриць K та L:\n", elementwise_multiplication)


Матриця K:
 [[9 9]
 [3 1]]
Матриця L:
 [[6 5]
 [8 5]]
Поелементне множення матриць K та L:
 [[54 45]
 [24  5]]


In [25]:
matrix_m = np.random.randint(1, 11, size=(2, 2))
matrix_n = np.random.randint(1, 11, size=(2, 2))
matrix_product_mn = np.dot(matrix_m, matrix_n)
print("\nМатриця M:\n", matrix_m)
print("Матриця N:\n", matrix_n)
print("Добуток матриць M та N:\n", matrix_product_mn)


Матриця M:
 [[ 4  6]
 [ 8 10]]
Матриця N:
 [[4 1]
 [7 5]]
Добуток матриць M та N:
 [[ 58  34]
 [102  58]]


In [24]:
matrix_o = np.random.randint(1, 101, size=(5, 5))
sum_elements_o = np.sum(matrix_o)
print("\nМатриця O:\n", matrix_o)
print("Сума елементів матриці O:\n", sum_elements_o)


Матриця O:
 [[72 42 12 39 68]
 [32 91 96 52 65]
 [12 85 18  9 68]
 [94 55 30 21 26]
 [94  3 37 96  4]]
Сума елементів матриці O:
 1221


In [23]:
matrix_p = np.random.randint(1, 11, size=(4, 4))
matrix_q = np.random.randint(1, 11, size=(4, 4))
difference_pq = matrix_p - matrix_q
print("\nМатриця P:\n", matrix_p)
print("Матриця Q:\n", matrix_q)
print("Різниця матриць P та Q:\n", difference_pq)


Матриця P:
 [[8 6 9 8]
 [9 2 9 8]
 [2 1 5 4]
 [8 4 9 6]]
Матриця Q:
 [[ 3  4  9  8]
 [10  8  1  9]
 [ 9  2  5  2]
 [ 8  8  7  2]]
Різниця матриць P та Q:
 [[ 5  2  0  0]
 [-1 -6  8 -1]
 [-7 -1  0  2]
 [ 0 -4  2  4]]


In [22]:
matrix_r = np.random.rand(3, 3)
sum_rows_r = np.sum(matrix_r, axis=1)
print("\nМатриця R:\n", matrix_r)
print("Суми елементів кожного рядка матриці R:\n", sum_rows_r)


Матриця R:
 [[0.98536419 0.20957751 0.15641295]
 [0.58613572 0.8047334  0.32982106]
 [0.76808684 0.74394196 0.71284027]]
Суми елементів кожного рядка матриці R:
 [1.35135466 1.72069018 2.22486907]


In [21]:
matrix_s = np.random.randint(1, 11, size=(3, 4))
matrix_s_squares = np.square(matrix_s)
print("\nМатриця S:\n", matrix_s)
print("Матриця з квадратами чисел матриці S:\n", matrix_s_squares)


Матриця S:
 [[ 5  3  6 10]
 [ 4  7  1  1]
 [ 4  8  9  1]]
Матриця з квадратами чисел матриці S:
 [[ 25   9  36 100]
 [ 16  49   1   1]
 [ 16  64  81   1]]


In [20]:
vector_g = np.random.randint(1, 51, size=4)
vector_g_sqrt = np.sqrt(vector_g)
print("\nВектор G:\n", vector_g)
print("Вектор з квадратними коренями чисел вектора G:\n", vector_g_sqrt)


Вектор G:
 [37  9 20  9]
Вектор з квадратними коренями чисел вектора G:
 [6.08276253 3.         4.47213595 3.        ]
